name: aisat_connect
description: "A decentralized, end-to-end encrypted messaging app utilizing the Nostr and Signal protocols."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bip39: ^1.0.6
  cryptography: ^2.9.0
  crypto: ^3.0.7
  web_socket_channel: ^3.0.3
  dart_nostr: ^10.0.1
  flutter_riverpod: ^2.5.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.5
  drift: ^2.34.4
  path_provider: ^2.1.6
  path: ^1.9.1
  libsignal_protocol_dart: ^0.7.2
  flutter_secure_storage: ^11.1.1
  sqlcipher_flutter_libs: ^0.7.0+eol
  connectivity_plus: ^7.3.1
  google_fonts: ^8.2.1
  window_manager: ^0.5.2
  flutter_svg: ^2.3.0
  mobile_scanner: ^7.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.16.1
  drift_dev: ^2.34.6
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  windows:
    generate: true
    icon_size: 256
  image_path: "assets/aisat_connect_logo.png"
  remove_alpha_ios: true
